### ISSUE TITLE
`jax.experimental.optimizers` has been removed since 0.3.16

### ISSUE THREAD

**Issue by mave240** [probml/probml-utils#33]
`jax.experimental.optimizers` had long been a deprecated alias of [jax.example_libraries.optimizers](https://jax.readthedocs.io/en/latest/jax.example_libraries.optimizers.html#module-jax.example_libraries.optimizers) before being removed in 0.3.16 (which is not versioned in `requirements*.txt`).

Solution would be to replace:
`from jax.experimental import optimizers`
with:
`from jax.example_libraries import optimizers`

**Comment by patel-zeel** [comment]
Good catch! And thank you, @mave240. I have incorporated your suggestion to fix the issue.
