### ISSUE TITLE
Installation fails in colab

### ISSUE THREAD

**Issue by hiraksarkar** [probml/probml-utils#34]
Hi, 

Thanks a lot for developing probml-util. The package installation fails currently in colab with the following error.
```
pip install -qq git+https://github.com/probml/probml-utils.git
```
Error -- 
```
ERROR: Could not build wheels for numba, llvmlite, which is required to install pyproject.toml-based projects
```

**Comment by patel-zeel** [comment]
Thank you for reporting this, @hiraksarkar. I have fixed the issue by adjusting the package versions. Feel free to reopen this issue if the problem persists.
