### ISSUE TITLE
importing probml_utils

### ISSUE THREAD

**Issue by cherrye22** [probml/probml-utils#35]
Hello;

I can't clone probml_utils from githup due to deprecation issues with setup.py it seems.  What is another way to use files in Jupyter notebook?  I'm new to Jupyter notebook so I can't seem to resolve.  I tried just running code for the Plot of various activation functions in Neural network but section of code that imports from githup will just not work.

**Comment by patel-zeel** [comment]
Hi @cherrye22, can you please provide us the error log so that we can look into the issue? Most probably the issue was related to conflicting `numpy` versions which is now resolved. Please reopen this issue and provide us the new error logs if it is still not resolved at your end.
